apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rverspaij/ArgoCD-PROD-.git
    targetRevision: HEAD
    path: apps/dev/chat-service
  destination:
    server: https://kubernetes.default.svc
    namespace: chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true