resources:
  - frontend-application.yaml
  - media-application.yaml
  - auth-application.yaml
  - rabbitmq-application.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml