apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: auth
type: Opaque
stringData:
  AzureBlob__ConnectionString: DefaultEndpointsProtocol=https;AccountName=mediastorageapp;AccountKey=xxx;EndpointSuffix=core.windows.net
  AzureBlob__ContainerName: media
