apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8080
  selector:
    io.kompose.service: auth-service
