apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: gateway
spec:
  selector:
    app: chat-service  # Zorg dat de Deployment in de `auth` namespace deze label heeft
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
