apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/rabbitmq-data-persistentvolumeclaim.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml

namespace: auth