apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rverspaij/argo-cd-gitops.git
    targetRevision: HEAD
    path: apps/dev/user-service/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true