apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-user/argo-cd-gitops.git
    targetRevision: HEAD
    path: apps/dev/user
  destination:
    server: https://kubernetes.default.svc
    namespace: user
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
