# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: auth

# resources:
#   - manifests/namespace.yaml
#   - manifests/env.yaml
#   - manifests/azure-secret.yaml
#   - manifests/deployment.yaml
#   - manifests/service.yaml
#   - manifests/ingress.yaml
#   - manifests/db-deployment.yaml
#   - manifests/db-service.yaml