# NGINX Gateway Fabric CRDs (v0.1.0)
# Downloaded from: https://github.com/nginxinc/nginx-gateway-fabric/releases/tag/v0.1.0

# Voorbeeld: NginxGateway CRD (volledige versie bevat meerdere CRDs)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxgateways.gateway.nginx.org
spec:
  group: gateway.nginx.org
  names:
    kind: NginxGateway
    listKind: NginxGatewayList
    plural: nginxgateways
    singular: nginxgateway
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
# ...
